fix: Remove pass-cli dependency

diff --git a/cloudflare-ddns b/cloudflare-ddns
--- a/cloudflare-ddns
+++ b/cloudflare-ddns
@@ -14,20 +14,19 @@ set -euo pipefail
 : "${DEBUG:=0}"
 
 if [[ $# -ne 1 || -z "$1" ]]; then
-    printf 'usage: %s <profile>\n' "$0" >&2
+    printf 'usage: %s <domain>\n' "$0" >&2
     exit 2
 fi
 if [[ "$1" == *[^a-zA-Z0-9_.-]* ]]; then
-    printf 'Invalid profile name: %s\n' "$1" >&2
+    printf 'Invalid domain name: %s\n' "$1" >&2
     exit 2
 fi
 
 source "${XDG_CONFIG_HOME:-$HOME/.config}/cloudflare-ddns/$1.env"
-: "${API_TOKEN_URI:?API_TOKEN_URI is not set}"
+: "${API_TOKEN:?API_TOKEN is not set}"
 : "${ZONE_ID:?ZONE_ID is not set}"
 : "${RECORD_ID:?RECORD_ID is not set}"
 : "${RECORD_NAME:?RECORD_NAME is not set}"
-API_TOKEN="$(pass-cli item view "$API_TOKEN_URI")"
 : "${TTL:=1200}"
 : "${PROXIED:=false}"
 
